#if defined _trophy_weapon_menu_included
 #endinput
#endif
#define _trophy_weapon_menu_included

#define INFO_SIZE 128
#define ITEM_SIZE 128

#define ASK_ABOUT_TROPHY_WEAPON_TIME 5

#define TROPHY_WEAPON "Trophy weapon"
#define ITEM_ASK "Ask"
#define ITEM_GIVE_ALWAYS "Always give"
#define ITEM_GIVE_NEVER "Never give"

#define GIVE_TROPHY_WEAPON "Give trophy weapon"
#define ITEM_YES "Yes"
#define ITEM_NO "No"
